name = "ImplicitGlobalGrid"
uuid = "4d7a3746-15be-11ea-1130-334b0c4f5fa0"
authors = ["Samuel Omlin", "Swiss National Supercomputing Centre"]
version = "0.9.3"

[compat]
julia = "1"
MPI = "≥ 0.12"
CUDA = "≥ 1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
